### ISSUE TITLE
注册页面的文本似乎有误?

### ISSUE THREAD

**Issue by the1812** [suwadaimyojin/patchyvideo-vue#76]
https://github.com/suwadaimyojin/patchyvideo-vue/blob/eba6ac14766cdfdd2ca5010d4268556af83c42eb/src/views/SignUp.vue#L30

https://github.com/suwadaimyojin/patchyvideo-vue/blob/eba6ac14766cdfdd2ca5010d4268556af83c42eb/src/views/SignUp.vue#L49

`input_psd`对应的应该是`请输入密码`之类的吧

**Comment by suwadaimyojin** [comment]
非常抱歉文本错误已修复，在下一次的更新部署中恢复正常

**Comment by the1812** [comment]
现在正常了 感谢修复
